name:               "Michelle Gray"
description:        "A minimalistic jekyll theme for humans"

url:                ""
author:             "mermaid"
email:              "michellecgray1%40gmail%2Ecom"
instagram:          "m.c._photography_"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
