name:               "Michelle Gray"
description:        "A minimalistic jekyll theme for humans"

url:                ""
author:             "mermaid"
email:              "michellecgray1%40gmail%2Ecom"
instagram:          "m.c._photography_"

initial-portfolio: adventure
portfolio: 
  - 
    id: "adventure"
    name: "Adventure"
    images: 
    - images/adventure/DakotaForest.jpg
    - images/adventure/DakotaTrainDesaturated.jpg
    - images/adventure/StarStruck.jpg
  -
    id: "landscape"
    name: "Landscape"
    images: 
    - images/landscape/BryceCrack.jpg
    - images/landscape/BryceThorsHammer.jpg
    - images/landscape/BryceWall.jpg
    - images/landscape/IMG_2751.jpg
    - images/landscape/IMG_2772.jpg
    - images/landscape/LavaPointEnteranceZion-3.jpg
    - images/landscape/LavaPointEnteranceZion-4.jpg
    - images/landscape/LookUpBryce.jpg
    - images/landscape/MilkyWay.jpg
    - images/landscape/TinyTree.jpg
    - images/landscape/Tree.jpg
  -
    id: "portrait"
    name: "Portrait"
    images: 
    - images/portrait/Bailey 2.jpg
    - images/portrait/Bailey 5.jpg
    - images/portrait/Bailey 6.jpg
    - images/portrait/IMG_9526.jpg
    - images/portrait/IMG_9533.jpg
    - images/portrait/IMG_9536.jpg
    - images/portrait/Marina-1.jpg
    - images/portrait/Marina-2.jpg
    - images/portrait/Marina-6.jpg
    
  -
    id: "wedding"
    name: "Wedding"
    images: 
    - images/wedding/Perez Wedding-346.jpg
    - images/wedding/Perez Wedding-323.jpg
    - images/wedding/Perez Wedding-312.jpg
    - images/wedding/Perez Wedding-272.jpg
    - images/wedding/Perez Wedding-270.jpg
    - images/wedding/Perez Wedding-236.jpg
    - images/wedding/Perez Wedding-210.jpg
    - images/wedding/Perez Wedding-154.jpg
    - images/wedding/Perez Wedding-17.jpg
        
background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
