name:               "Michelle Holiman"
description:        "Photographer"

url:                ""
author:             "mermaid"
email:              "michellecholiman%40gmail%2Ecom"
instagram:          "m.c._photography_"
facebook:           "PhotoMichelleChristine"

initial-portfolio: adventure
portfolio: 
  - 
    id: "adventure"
    name: "Adventure"
    images: 
    - images/adventure/adventure-1
    - images/adventure/adventure-2
    - images/adventure/adventure-3
    - images/adventure/adventure-4
    - images/adventure/adventure-5
    - images/adventure/adventure-6
    - images/adventure/adventure-7
    - images/adventure/adventure-8
    - images/adventure/adventure-9
    - images/adventure/adventure-10
    - images/adventure/adventure-11
    - images/adventure/adventure-12
  -
    id: "people"
    name: "People"
    images:
    - images/people/people-1
    - images/people/people-2
    - images/people/people-3
    - images/people/people-4
    - images/people/people-5
    - images/people/people-6
    - images/people/people-7
    - images/people/people-8
    - images/people/people-9
    - images/people/people-10
    - images/people/people-11
    - images/people/people-12
  # -
  #   id: "wedding"
  #   name: "Wedding"
  #   images: 
  #   - images/wedding/Perez Wedding-346.jpg
  #   - images/wedding/Perez Wedding-323.jpg
  #   - images/wedding/Perez Wedding-312.jpg
  #   - images/wedding/Perez Wedding-272.jpg
  #   - images/wedding/Perez Wedding-270.jpg
  #   - images/wedding/Perez Wedding-236.jpg
  #   - images/wedding/Perez Wedding-210.jpg
  #   - images/wedding/Perez Wedding-154.jpg
  #   - images/wedding/Perez Wedding-17.jpg
  #   - images/wedding/web-1.jpg
  #   - images/wedding/web-2.jpg
  #   - images/wedding/web-3.jpg
  #   - images/wedding/web-4.jpg
  #   - images/wedding/web-5.jpg
  #   - images/wedding/web-6.jpg
  #   - images/wedding/web-7.jpg
  #   - images/wedding/web-8.jpg
  -
    id: "wildlife"
    name: "Wildlife"
    images:
    - images/wildlife/wildlife-1
    - images/wildlife/wildlife-2
    - images/wildlife/wildlife-3
    - images/wildlife/wildlife-4
    - images/wildlife/wildlife-5
    - images/wildlife/wildlife-6
    - images/wildlife/wildlife-7
    - images/wildlife/wildlife-8
    - images/wildlife/wildlife-9
    - images/wildlife/wildlife-10
    - images/wildlife/wildlife-11
    - images/wildlife/wildlife-12


background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
